/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ieee80211cu
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_IEEE80211CU_API_H
#define INCLUDED_IEEE80211CU_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ieee80211cu_EXPORTS
#define IEEE80211CU_API __GR_ATTR_EXPORT
#else
#define IEEE80211CU_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_IEEE80211CU_API_H */
