/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demodcu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(604c7d00d781e54fd11b219041aa3626)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211cu/demodcu.h>
// pydoc.h is automatically generated in the build directory
#include <demodcu_pydoc.h>

void bind_demodcu(py::module& m)
{

    using demodcu    = ::gr::ieee80211cu::demodcu;


    py::class_<demodcu, gr::block, gr::basic_block,
        std::shared_ptr<demodcu>>(m, "demodcu", D(demodcu))

        .def(py::init(&demodcu::make),
           py::arg("mupos"),
           py::arg("mugid"),
           py::arg("ifdebug"),
           D(demodcu,make)
        )
        



        ;




}








