/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demodcu2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a743cbd9cb0261948412e3ef7e712d10)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211cu/demodcu2.h>
// pydoc.h is automatically generated in the build directory
#include <demodcu2_pydoc.h>

void bind_demodcu2(py::module& m)
{

    using demodcu2    = ::gr::ieee80211cu::demodcu2;


    py::class_<demodcu2, gr::block, gr::basic_block,
        std::shared_ptr<demodcu2>>(m, "demodcu2", D(demodcu2))

        .def(py::init(&demodcu2::make),
           py::arg("ifdebug"),
           D(demodcu2,make)
        )
        



        ;




}








