/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(genpkt.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8a4feeb273032b62760252e8bb6552f9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211cu/genpkt.h>
// pydoc.h is automatically generated in the build directory
#include <genpkt_pydoc.h>

void bind_genpkt(py::module& m)
{

    using genpkt    = ::gr::ieee80211cu::genpkt;


    py::class_<genpkt, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<genpkt>>(m, "genpkt", D(genpkt))

        .def(py::init(&genpkt::make),
           py::arg("lengthtagname") = "packet_len",
           D(genpkt,make)
        )
        



        ;




}








