/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preproccu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c47add3350b0aa543bd8598e2f7d28dd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211cu/preproccu.h>
// pydoc.h is automatically generated in the build directory
#include <preproccu_pydoc.h>

void bind_preproccu(py::module& m)
{

    using preproccu    = gr::ieee80211cu::preproccu;


    py::class_<preproccu, gr::block, gr::basic_block,
        std::shared_ptr<preproccu>>(m, "preproccu", D(preproccu))

        .def(py::init(&preproccu::make),
           D(preproccu,make)
        )
        



        ;




}








